name: Create and Push Runpod Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # to allow building multi-arch images, uncomment the following lines
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3
      # and then uncomment the platforms line in the build-and-push step below

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ollama-runpod:latest
          #latforms: linux/amd64,linux/arm64 # uncomment this line to enable multi-arch builds
